project:
  type: website

website:
  title: "Blog-Dairy Production and Consumption"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Harshk1202
format:
  html:
    theme: superhero
    css: styles.css



