project:
  type: website

website:
  title: "Blog-Dairy Production and Consumption"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Harshk1202
      - icon: linkedin
        href: https://www.linkedin.com/in/harsh-katiyar-796aab179/
format:
  html:
    theme: superhero
    css: styles.css



